"""The answer-key runner: the generated harness, tare.json validation, and a real GnuCOBOL run."""
import json
import shutil
import tempfile
import unittest
from pathlib import Path

from tare import answerkey, config, records
from tests.helpers import EXAMPLE, has_cobc, load

NOOP = """\
      * TEST FIXTURE: shows its PARM and returns.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. NOOP.
       DATA DIVISION.
       LINKAGE SECTION.
       01  RUN-PARM.
           05 RUN-PARM-LENGTH         PIC S9(04) COMP.
           05 RUN-PARM-TEXT           PIC X(100).
       PROCEDURE DIVISION USING RUN-PARM.
           IF ADDRESS OF RUN-PARM NOT = NULL
               DISPLAY 'NOOP: [' RUN-PARM-TEXT(1:RUN-PARM-LENGTH) ']'
           END-IF
           GOBACK.
"""
PARM = "IT'S A LONGER PARM, OVER THIRTY CHARACTERS: 12345"

# 12-byte records: code X(4) at 0 (primary key), group X(2) at 4 (alternate key, duplicates), qty 9(6) at 6
ROWS = ["C003AA000030", "A001BB000010", "B002AA000020", "D004CC000040"]


def mini_case(root: Path):
    (root / "cbl").mkdir()
    (root / "cbl" / "NOOP.cbl").write_text(NOOP, encoding="utf-8")
    (root / "data").mkdir()
    (root / "data" / "rows.txt").write_text("\n".join(ROWS) + "\n", encoding="utf-8")
    lay = {"record_length": 12, "key": ["code"], "fields": [
        {"name": "code", "offset": 0, "length": 4, "type": "X"},
        {"name": "grp", "offset": 4, "length": 2, "type": "X"},
        {"name": "qty", "offset": 6, "length": 6, "type": "9"}]}
    cfg = {"cobol": {"sources": ["cbl/NOOP.cbl"], "copybooks": []},
           "files": {"master": {"from": "data/rows.txt", "from_format": "lines", "record_length": 12,
                                "organization": "indexed", "key": {"offset": 0, "length": 4},
                                "alternate_keys": [{"offset": 4, "length": 2, "duplicates": True}],
                                "layout": "ROW", "output": True},
                     "plain": {"from": "data/rows.txt", "from_format": "lines", "record_length": 12,
                               "layout": "ROW", "output": True}},
           "steps": [{"program": "NOOP", "parm": PARM, "dd": {"MASTER": "master"}}],
           "layouts": {"ROW": lay}}
    (root / "tare.json").write_text(json.dumps(cfg, indent=2), encoding="utf-8")
    return cfg


class Generated(unittest.TestCase):
    def test_loader_declares_every_key_within_72_columns(self):
        with tempfile.TemporaryDirectory() as td:
            cfg = mini_case(Path(td))
        src = answerkey.loader_source(cfg)
        self.assertTrue(src.startswith("      *HARNESS: generated by tare/answerkey.py"))
        self.assertIn("RECORD KEY   IS IDX-01-KEY0", src)
        self.assertIn("ALTERNATE RECORD KEY IS IDX-01-KEY1", src)
        self.assertIn("WITH DUPLICATES", src)
        self.assertTrue(all(len(l) <= 72 for l in src.splitlines()))

    def test_parm_driver(self):
        src = answerkey.parm_driver_source(3, "PROG", PARM)
        self.assertIn("PROGRAM-ID. TPARM03.", src)
        self.assertIn(f"MOVE {len(PARM)} TO JCL-PARM-LENGTH", src)
        self.assertIn("MOVE 'IT''S A LONGER PARM, OVER THIRT'\n             TO JCL-PARM-TEXT(1:30)", src)
        self.assertIn("CALL 'PROG' USING JCL-PARM", src)
        self.assertTrue(src.startswith("      *HARNESS:"))

    def test_validation(self):
        with tempfile.TemporaryDirectory() as td:
            cfg = mini_case(Path(td))
        bad = json.loads(json.dumps(cfg))
        bad["steps"][0]["dd"]["X"] = "nosuchfile"
        with self.assertRaises(answerkey.AnswerKeyError):
            answerkey.validate(bad)
        bad = json.loads(json.dumps(cfg))
        bad["steps"][0]["parm"] = "x" * 101
        with self.assertRaises(answerkey.AnswerKeyError):
            answerkey.validate(bad)
        bad = json.loads(json.dumps(cfg))
        bad["files"]["master"]["key"] = {"offset": 10, "length": 4}
        with self.assertRaises(answerkey.AnswerKeyError):
            answerkey.validate(bad)
        answerkey.validate(load("tare.json"))


@unittest.skipUnless(has_cobc(), "GnuCOBOL (cobc, cobcrun) not on PATH")
class RealRun(unittest.TestCase):
    def test_loader_round_trip_parm_and_sequential_output(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            mini_case(root)
            s = answerkey.build(root, say=lambda _: None)
            self.assertEqual(s["records"], {"master": 4, "plain": 4})
            out = root / config.ANSWER_DIR
            # loaded in any order, unloaded in primary key order; the sequential file is copied as it was
            self.assertEqual((out / "master.dat").read_bytes(), "".join(sorted(ROWS)).encode())
            self.assertEqual((out / "plain.dat").read_bytes(), "".join(ROWS).encode())
            self.assertEqual((out / "input" / "master.dat").read_bytes(), "".join(ROWS).encode())
            log = (out / "logs" / "step01_NOOP.log").read_text(encoding="latin-1")
            self.assertIn(f"NOOP: [{PARM}]", log)
            doc = records.load_side(out / "records.json")
            self.assertEqual(doc["files"]["master"][0], {"code": "A001", "grp": "BB", "qty": "10"})
            self.assertEqual(doc["side"], "answer_key")

    def test_refuses_to_replace_a_folder_that_is_not_an_answer_key(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            mini_case(root)
            (root / "keep").mkdir()
            (root / "keep" / "notes.txt").write_text("x", encoding="utf-8")
            with self.assertRaises(answerkey.AnswerKeyError):
                answerkey.build(root, "keep", say=lambda _: None)
            self.assertTrue((root / "keep" / "notes.txt").is_file())

    def test_the_committed_example_reproduces(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            shutil.copy(EXAMPLE / "tare.json", root / "tare.json")
            shutil.copytree(EXAMPLE / "mainframe", root / "mainframe")
            answerkey.build(root, "fresh", say=lambda _: None)
            self.assertEqual(answerkey.compare(EXAMPLE / config.ANSWER_DIR, root / "fresh", load("tare.json")), [])


if __name__ == "__main__":
    unittest.main()
