from pathlib import Path

from . import config

SIGNS = {
    "trailing-overpunch": "signed, the sign in the last digit's zone (see below)",
    "separate": "signed, a trailing `+` or `-` byte after the digits",
    "none": "unsigned",
}
PACKED = "packed decimal: two digits a byte, the sign in the last half-byte (C positive, D negative, F unsigned)"


def _pic(f: dict) -> str:
    t, n, s = f.get("type", "X"), f["length"], int(f.get("scale", 0))
    if t == "X":
        return f"X({n})"
    if t == "COMP-3":
        return f"S9({2 * n - 1 - s})" + (f"V9({s})" if s else "") + " COMP-3"
    digits = n - (1 if f.get("sign") == "separate" else 0)
    head = "S" if t == "S9V9" else ""
    return f"{head}9({digits - s})" + (f"V9({s})" if s else "")


def _table(layout: dict) -> list:
    o = ["| offset | length | field | COBOL name | picture | encoding |", "|---:|---:|---|---|---|---|"]
    for f in layout["fields"]:
        t = f.get("type", "X")
        dec = f", {f.get('scale')} implied decimals" if f.get("scale") else ""
        if t == "X":
            enc = "text, space padded"
        elif t == "COMP-3":
            enc = PACKED + dec
        else:
            enc = SIGNS.get(f.get("sign", "trailing-overpunch" if t == "S9V9" else "none"), "") + dec
        o.append(f"| {f['offset']} | {f['length']} | `{f['name']}` | {f.get('cobol', '')} | {_pic(f)} | {enc} |")
    return o


def render(root: Path) -> str:
    cfg = config.load_config(root)
    if not cfg:
        raise ValueError(f"no tare.json at {root}")
    files = cfg.get("files") or {}
    prog = cfg.get("program") or ", ".join(s.get("program", "?") for s in cfg.get("steps", []))
    srcs = ", ".join(f"`{s}`" for s in (cfg.get("cobol") or {}).get("sources", []))
    o = [f"# Port contract: {prog}", "",
         f"Generated by `python -m tare contract` from `tare.json`; edit `tare.json`, not this file.",
         *([f"", f"> {cfg['about']}"] if cfg.get("about") else []), "",
         f"The original program is {srcs} with the copybooks in "
         + ", ".join(f"`{d}`" for d in (cfg.get("cobol") or {}).get("copybooks", [])) + ". "
         "Its output, recorded by `python -m tare answer-key` in `fixtures/answer_key/`, is the answer key. "
         "Your port is the Java program under `port/`. Tare builds it, runs it on the answer key's own input "
         "and weighs its output against the answer key, record by record and field by field.", "",
         "## Command line", "",
         "`python -m tare run-port local` compiles every `.java` file under `port/` with `javac` and runs the "
         "class named on the first line of `port/MAIN`:", "",
         "```", "java -cp <classes> <MAIN> --input <input dir> --out <output dir>", "```", "",
         "Use only the JDK. The program runs with its working directory in `work/sandbox/local/`, which holds "
         "only copies of the input files and the compiled classes: read through `--input`, write through "
         "`--out`, never by a path into the repository. It must exit 0. The MCP tools are `run_port` and "
         "`weigh` with side `local`.", "",
         "## Input files (`fixtures/answer_key/input/`)", "",
         "Fixed-width records with no record separators. Offsets are 0-based bytes."]
    for name in config.inputs(cfg):
        f = files[name]
        o += ["", f"**`{name}.dat`**, {f.get('record_length')} bytes per record"
              + (f", organization {f['organization']}" if f.get("organization") else "") + "."]
        lay = (cfg.get("layouts") or {}).get(f.get("layout"))
        if lay:
            o += ["", *_table(lay)]
    o += ["", "## Output files", "",
          "Write each file below to `<output dir>/<file>.dat`, fixed-width, one record after another with no "
          "separators, exactly as the original program writes it: the same record length, field positions, "
          "padding and number encoding. Write the records of an indexed file in ascending key order."]
    for name in config.outputs(cfg):
        f = files[name]
        lay = config.layout_for(cfg, name)
        o += ["", f"**`{name}.dat`**, {lay['record_length']} bytes per record, key "
              + ", ".join(f"`{k}`" for k in lay["key"]) + ".", "", *_table(lay)]
    o += ["", "Bytes not covered by a field are filler: write spaces.", "",
          "### Signed numbers", "",
          "A trailing-overpunch field is all digits, with the sign carried in the zone of the last byte:", "",
          "| last byte | digit | sign |", "|---|---|---|",
          "| `0`-`9` | same digit | + |", "| `{`, `A`-`I` | 0, 1-9 | + |", "| `}`, `J`-`R` | 0, 1-9 | - |",
          "| `p`-`y` | 0-9 | - |", "",
          "GnuCOBOL writes the letter forms with `-fsign=EBCDIC`"
          + (" (this answer key was built with it)" if "-fsign=EBCDIC" in ((cfg.get("cobol") or {}).get("flags")
                                                                         or []) else "")
          + "; write what the answer key's files hold.", "",
          "## What the program must do", "",
          f"Exactly what {srcs} does, with its copybooks. The COBOL source is the specification; read it, not "
          "a summary.", "",
          "## How the weigh judges it", "",
          "Tare decodes your files and the answer key's with the layouts above. Records are matched by key; "
          "every declared field is compared, numbers in decimal. The weigh is balanced only when every field "
          "of every record is equal and no record is missing or extra. `tare.json` lists differences a person "
          "has accepted (under `accepted`, signed with `python -m tare accept`); an accepted difference does "
          "not turn the weigh red, and every weigh still shows it. The gate hashes `port/**/*.java` and "
          "`port/MAIN` at each weigh; any later edit needs a new weigh before a commit.", ""]
    return "\n".join(o)


def target(root: Path) -> Path:
    for d in (root, *root.parents):
        if (d / ".bob").is_dir():
            return d / ".bob" / "skills" / "replay" / "PORT_CONTRACT.md"
    return root / ".bob" / "skills" / "replay" / "PORT_CONTRACT.md"


def write(root: Path, out=None) -> Path:
    p = Path(out) if out else target(Path(root).resolve())
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(render(root), encoding="utf-8", newline="\n")
    return p
